config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  resources :users, param: :user_name do
    member do
      get 'favorites' => 'favorites#index'
      get 'followers'
      get 'followings'
      resource :relationships, only: [:create, :destroy]
    end
  end

  resources :books, param: :book_id do
    member do
      resource :favorites, only: [:create, :destroy]
      resource :book_comment, only: [:create, :destroy]
    end
  end
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  before_action :sign_in_required
  before_action :set_book, except: [:index]

  def index
    user = User.find_by(name: params[:user_name])
    @books = user.favorite_books.includes(:user, :favorites).page(params[:page]).per(20)
  end

  # お気に入り登録
  def create
    favorite = current_user.favorites.build(book_id: @book.id)
    favorite.save
  end

  # お気に入り削除
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, book_id: @book.id)
    favorite.destroy
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/views/favorites/_book.html.erb
<% if book.favorited_by?(user) %>
  <%= link_to favorites_path(book.id),method: :delete,remote: true do %>
    <span class="glyphicon glyphicon-heart">お気に入り数:<%= count %></span>
  <% end %>
<% else %>
  <%= link_to favorites_path(book.id), method: :post,remote:true do %>
    <span class="glyphicon glyphicon-heart-empty">お気に入り数:<%= count %></span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#<%= "table__favorite--" +@book.id.to_s %>').html("<%= j(render 'favorites/book',book: @book, user: current_user,count: @book.favorites.size) %>");

app/views/favorites/destroy.js.erb
$('#<%= "table__favorite--" +@book.id.to_s %>').html("<%= j(render 'favorites/book',book: @book, user: current_user,count: @book.favorites.size) %>");

app/views/favorites/index.html.erb
<h2>お気に入り一覧</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>ユーザー名</th>
      <th>タイトル</th>
      <th>紹介文</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.name) do %>
            <%= attachment_image_tag(book.user, :profile_image, size: "40x40", fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= book.user.name %></td>
        <td><%= link_to book.title,book_path(book) %></td>
        <td><%= book.description.truncate(20) %></td>
        <td id=<%= "table__favorite--" + book.id.to_s %>>
            <%= render 'favorites/book',book: book, user: current_user,count: book.favorites.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @books %>