config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  resources :users, param: :user_name do
    member do
      get 'favorites' => 'favorites#index'
      get 'followers'
      get 'followings'
      resource :relationships, only: [:create, :destroy]
    end
  end

  resources :books, param: :book_id do
    member do
      resource :favorites, only: [:create, :destroy]
      resource :book_comment, only: [:create, :destroy]
    end
  end
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
# frozen_string_literal: true

class RelationshipsController < ApplicationController
  before_action :set_user
  before_action :sign_in_required

  def create
    current_user.follow(@user)
    flash[:success] = 'ユーザーをフォローしました'
  end

  def destroy
    current_user.unfollow(@user)
    flash[:success] = 'ユーザーのフォローを解除しました'
  end

  private

  def set_user
    @user = User.find_by(name: params[:user_name])
  end
end

app/helpers/relationships_helper.rb
# frozen_string_literal: true

module RelationshipsHelper
end

app/views/relationships/_follow-button.html.erb
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", relationships_path(user.name), method: :delete,remote: true, class:"btn btn-default"%>
    <% else %>
      <%= link_to "フォローする", relationships_path(user.name), method: :post, remote: true,class:"btn btn-primary"%>
    <% end %>

app/views/relationships/create.js.erb
$("#follow-button_<%= @user.id %>").html("<%= j(render 'relationships/follow-button', user: @user) %>");
$("#following-count_<%= @user.id %>").html('<p>フォロー中</p><%= link_to "#{@user.followings.count}人",followings_user_path(@user.name) %>');
$("#follower-count_<%= @user.id %>").html('<p>フォロワー</p><%= link_to "#{@user.followers.count}人",followers_user_path(@user.name) %>');

app/views/relationships/destroy.js.erb
$("#follow-button_<%= @user.id %>").html("<%= j(render 'relationships/follow-button', user: @user) %>");
$("#following-count_<%= @user.id %>").html('<p>フォロー中</p><%= link_to "#{@user.followings.count}人",followings_user_path(@user.name) %>');
$("#follower-count_<%= @user.id %>").html('<p>フォロワー</p><%= link_to "#{@user.followers.count}人",followers_user_path(@user.name) %>');