config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  resources :users, param: :user_name do
    member do
      get 'favorites' => 'favorites#index'
      get 'followers'
      get 'followings'
      resource :relationships, only: [:create, :destroy]
    end
  end

  resources :books, param: :book_id do
    member do
      resource :favorites, only: [:create, :destroy]
      resource :book_comment, only: [:create, :destroy]
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

require 'open-uri'
class User < ApplicationRecord
  # deviseモジュール設定
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { maximum: 15, minimum: 3 }
  validates :introduction, length: { maximum: 200 }

  # フォローしている人達
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow

  # フォロワー
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy, inverse_of: :follow
  has_many :followers, through: :reverse_of_relationships, source: :user

  attachment :profile_image

  # OAuth

  def self.from_omniauth(auth)
    user = User.find_by(uid: auth.uid, provider: auth.provider)
    user ||= User.create(
      uid:            auth.uid,
      provider:       auth.provider,
      profile_image:  URI.parse(auth.info.image).open,
      email:          User.dummy_email(auth),
      name:           auth.info.name,
      password:       Devise.friendly_token[0, 20]
    )
    user
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes']) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  # follow

  def follow(other_user)
    self.relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship&.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
    else
      session['devise.twitter_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url, flash: { alert: 'すでに同じ名前のアカウントが存在するため登録できませんでした' }
    end
  end

  def failure
    redirect_to new_user_registration_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :sign_in_required
  before_action :set_user

  def rank
    # ランキング機能想定
  end

  def followers
    @users = @user.followers.includes(:followings, :followers).page(params[:page]).per(20)
  end

  def followings
    @users = @user.followings.includes(:followings, :followers).page(params[:page]).per(20)
  end

  def show
    @books = @user.books.includes(:favorites).order(created_at: :desc).page(params[:page]).per(20)
  end

  def edit
    # set_userのみ
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.name)
    else
      @user.name = params[:user_name]
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def set_user
    @user = User.find_by(name: params[:user_name])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>

<%= form_with(model:@user,local:true,url: user_path(@user.name)) do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field row">
    <%= f.text_field :name,placeholder:"名前", class: "col-sm mb-2 form-control" %>
  </div>

  <div class="field row">
    <div class="col-sm mb-2 form-control">
      <%= f.label :image,"プロフィール画像" %>
      <%= f.attachment_field :profile_image %>
    </div>
  </div>

  <div class="field row">
    <%= f.text_area :introduction,placeholder:"プロフィール文" ,class: "introduction col-sm mb-4 form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary col-sm"%>
  </div>
<% end %>

app/views/users/followers.html.erb
<h2>フォロー一覧</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>ユーザー名</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user.name) do %>
            <%= attachment_image_tag(user, :profile_image, size: "40x40", fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>フォロワー:<%= user.followers.size %>人</td>
        <td>フォロー中: <%= user.followings.size %>人</td>
        <td>    
            <% unless user == current_user %>
                <div id="follow-button_<%= user.id %>">
                    <%= render 'relationships/follow-button',user: user %>
                </div>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/users/followings.html.erb
<h2>フォロワー一覧</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>ユーザー名</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user.name) do %>
            <%= attachment_image_tag(user, :profile_image, size: "40x40", fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>フォロワー:<%= user.followers.size %>人</td>
        <td>フォロー中: <%= user.followings.size %>人</td>
        <td>    
            <% unless user == current_user %>
                <div id="follow-button_<%= user.id %>">
                    <%= render 'relationships/follow-button',user: user %>
                </div>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-sm-4">
        <div class="row">
            <div class="col-12">
                <%= attachment_image_tag @user, :profile_image,size: "100x100",fallback: "no_image.jpg" %>
            </div>
            <div class="col-12">
                <%= @user.name %>
            </div>
            <div class="col-12">
                <%= @user.introduction %>
            </div>
            <div class="col-lg-6" id="following-count_<%= @user.id %>">
                <p>フォロー中</p>
                <%= link_to "#{@user.followings.count}人",followings_user_path(@user.name) %>
            </div>
            <div class="col-lg-6" id="follower-count_<%= @user.id %>">
                <p>フォロワー</p>
                <%= link_to "#{@user.followers.count}人",followers_user_path(@user.name) %>
            </div>
            <div class="col-12">
                <p>お気に入り一覧</p>
                <%= link_to "#{@user.favorites.count}個",favorites_user_path %>
            </div>
            <div class="my-3 col-12">
                <% unless @user == current_user %>
                    <div id="follow-button_<%= @user.id %>">
                        <%= render 'relationships/follow-button',user:@user %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <h3>投稿一覧</h3>
        <table class='table table-hover table-inverse'>
          <tbody>
            <% @books.each do |book| %>
            <tr>
                <td><%= link_to book.title,book_path(book) %></td>
                <td><%= book.description.truncate(20) %></td>
                <td>お気に入り:<%= book.favorites.size %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @books %>
    </div>
</div>