config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  resources :users, param: :user_name do
    member do
      get 'favorites' => 'favorites#index'
      get 'followers'
      get 'followings'
      resource :relationships, only: [:create, :destroy]
    end
  end

  resources :books, param: :book_id do
    member do
      resource :favorites, only: [:create, :destroy]
      resource :book_comment, only: [:create, :destroy]
    end
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    Favorite.where(user_id: user.id, book_id: self.id).exists?
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_required

  def index
    @books = Book.all.includes(:user, :favorites, :book_comments).order(created_at: :desc).page(params[:page]).per(20)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def show
    @comment = BookComment.new
  end

  def edit
    # set_bookのみ
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description)
  end

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_detail.html.erb
<div class="row border-bottom">
    <div class="col-md-3"><%= book.title %></div>
    <div class="col-md-5" style="word-break: break-all;"><%= book.description %></div>
    <div  class="col-md-2" id=<%= "table__favorite--" + book.id.to_s %>>
      <%= render 'favorites/book',book: book, user: current_user,count: book.favorites.count %>
    </div>
    <div  class="col-md-2">コメント数: <%= book.book_comments.count %></div>
    <% if book.user == current_user %>
      <div  class="col-md"><%= link_to '編集', edit_book_path(book), class: "btn-sm btn-success" %></div>
      <div  class="col-md"><%= link_to '削除', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger"%></div>
    <% end %>
</div>

app/views/books/edit.html.erb
<h2>投稿本編集</h2>

<%= form_with(model:@book,local:true) do |f| %>
  <%= render 'layouts/errors', obj: @book %>

  <div class="field row">
    <%= f.text_field :title,placeholder:"タイトル", class: "col-sm mb-2 form-control" %>
  </div>

  <div class="field row">
    <%= f.text_area :description,placeholder:"紹介文" ,class: "introduction col-sm mb-4 form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary col-sm"%>
  </div>
<% end %>

app/views/books/index.html.erb
<h2>新着一覧</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th>投稿者</th>
      <th>タイトル</th>
      <th>おすすめ文</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.name) do %>
            <%= attachment_image_tag(book.user, :profile_image, size: "40x40", fallback: "no_image.jpg") %>
          <% end %>
          <%= book.user.name %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.description.truncate(20) %></td>
        <td id=<%= "table__favorite--" + book.id.to_s %>>
          <%= render 'favorites/book', book: book, user: current_user,count: book.favorites.size %>
        </td>
        <td>コメント数: <%= book.book_comments.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @books %>

app/views/books/new.html.erb
 <h3>新規投稿</h3>
<%= render 'layouts/errors', obj:@book %>
  <%= form_for(@book) do |f| %>
  <div class="field row">
    <%= f.text_field :title,placeholder:"タイトル", class: "col-sm mb-2 form-control"%>
  </div>

  <div class="field row">
    <%= f.text_area :description,placeholder:"本文", class: 'col-sm mb-5 form-control'%>
  </div>

  <div class="actions row">
    <%= f.submit "投稿する",class: 'btn btn-primary col-sm'%>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="row">
<div class="col-4 alert alert-info p-3">
    <div class="row">
      <div class="col-lg-6"><%= link_to user_path(@book.user.name) do %>
        <%= attachment_image_tag(@book.user, :profile_image, size:"100x100", fallback: "no_image.jpg") %><br>
        <% end %>
      </div>
      <div class="col-lg-6">
        <%= @book.user.name %>
      </div>
    </div>
</div>
<div class="col-8">
  <div id="datail__table">
    <%= render 'detail', book: @book %>
  </div>
  <div class="col-12" id="comment__table">
    <%= render 'book_comments/table', book_comments: @book.book_comments %>
  </div>
  <div id="error_explanation"></div>
    <%= form_with(model: [@book, @comment],remote: true, url: book_comment_path) do |f|%>
      <%= f.text_area :comment,placeholder: "コメント",rows:"3",id:"book_comment" %>
      <%= f.submit "送信", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>